plugins:
  markdownlint:
    enabled: true
    checks:
      MD006:
        enabled: false
      MD013:
        enabled: false
      MD033:
        enabled: false
      MD026:
        enabled: false
  shellcheck:
    enabled: true
    checks:
      SC2154:
        enabled: false
