sudo: required
language: python
python:
- '2.7'
services:
- docker
branches:
  except:
  - gh-pages
before_install:
- chmod +x ./after-effects
- chmod +x ./tests/*.sh
jobs:
  include:
  - stage: Shellcheck
    env: TEST_ENV="Shellcheck"
    script: "./tests/test-shell-scripts.sh"
  - stage: Docker
    env: TEST_ENV="Xenial-Docker"
    script: ./tests/test-distro.sh "ubuntu" "xenial"
  - env: TEST_ENV="Bionic-Docker"
    script: ./tests/test-distro.sh "ubuntu" "bionic"
  - env: TEST_ENV="Trusty"
    script: ./tests/test-distro.sh "ubuntu" "trusty"
  - env: TEST_ENV="Debian9-Docker"
    script: ./tests/test-distro.sh "debian" "stretch"
  - env: TEST_ENV="Debian8-Docker"
    script: ./tests/test-distro.sh "debian" "jessie"
  - env: TEST_ENV="Cosmic-Docker"
    script: "./tests/test-prerelease.sh"
  - stage: Documentation & Deploy
    env: TEST_ENV="Docs-Build"
    script: "./tests/test-docs.sh"
    deploy:
    - provider: pages
      skip_cleanup: true
      deployment-file: false
      local-dir: _site
      skip-cleanup: true
      keep-history: true
      target-branch: gh-pages
      email:
        secure: dq/+hKw1qcf0OzeqPmcXZJMrOTn/sEEa0SuqagtzVchbvrkBc3gNWcRnG960nlZS7sL4Jdtmp3rm1dfPJl9a3R9Ra6rWzK8j1MEA8/N8BCi0y1NbQP/gHCHooEDJq3Jz2PJzZA/f5+qlR7b7Vs0xmZRfHwcsQy9FKd8mwTcQ8n4V7P3F/1FfrOgNyr5J/r5zlzHNhwVbshrJyDivX7rl6rpIKsDmXNEM7DEws9AeNlsLgeQRtl77+U04h4CHQD8Y9N5hj+Rh4OJL5V1NVhN8/zOMsfp1lZuj9OWWapRDmpV7Y9CDY8bGAmxuG5QP6CIe2f+PoSXWZw4Y20pLN2ke4GSHhWzX0nElKh9iv3v/wb6Hitsbk4xvSAJ71+BNzQFJOIBwCdBTNMQY3JExG9CrxPylMlGFnyEfQytYnEZAzwSy26smJREvcDi+d1eM5I8RLhp3OhOaQw6/xxTEcMCf5qCuYbDVGnx3mO8UQ52c6Fjd+CQ5BVaKAK1uSSRfIyxQS2CgVVrIKVT1s+ooChuM1BHjn3CW1EcMWiQ/KJO1hjTJ+GV7CB5xA99m04GsI5QASfFvPO1xzlx7elI6vPkIvjVH38ixMEo/evVZN35HlUgpEgQ7YNgRnP4iyAmPcYGmjpzXKl7CZtjpIamWiLQX8xrF15+enxueAznJLCvJ5vk=
      name:
        secure: baNHTRiPiXoa/qEuSjnIvzoxvHZ+RlQZdI+dcvoCQR+aJaJxB9iOR/i/T1qvjaB6meHjwQuSoXYssaKRlrjM4baQJbaN+7aHh8N9x9l7kUaG9tPmIwV78FRAjYlu1jNiFwnTzZyA2kYbQRUdren2sSbBZl31CCOQ/ykMvg3NbYx6po+bE5JrNuGZtKCdtw6Yh9TD/wDlPQS9b3czztyT1GjSW5Lkkrm0USSy4weY905K1drQTmhYMWWQ66qyApqD8QVxqM0EG+PCkZloq+X8qZXC5Q/6Z+V1XTHOP6xrZZpZmh/WoHsJT/LiQxxnlAAHZMx2PEA/S/c+0cLEIQh4NQ5IGrGfhNgWoV4mzR9iWgALEeaVMM5O4sk0Lg2/NvyvIEWQrdUdgF4sTNTUv8RFBa+MrVbwz3TvmS/BQDPTZ1GhephIm0T47w8l+bILfSNayqNDDcM0ltMNUemwifH5BmB9P2ut3RNvp916wvpE++0qNHxHD1ylpvMCvsPqyGXGCPfayQ7kpRjA3Tjx8ZZteTmAFFzb6U0H75CEtINr3jBtvuNYlse8oI9s6SGCW3ZCCzpZsZPOkk1DveQ2BlgKJrBoqqwE8h5p17zQp8fyj7ckV9QlM4eHJB0jf930czUOMUcJcomjlR9EDn2ddNlAPxuAU12z1EX2F0oS0+DZA7M=
      github-token:
        secure: oRr7HXuHUseOhfI7+gIP9pKleVed+6X8iS/aCSPnZxWPISemFAxki5Kx5sLr+6O6u3Sm1pZ4aVE5KDQ8akNmuoAeeC0UVgjYnt1vlbHaMYCzTkRW4ObrB6QjGQHOJuFUaTZPEX06LfdRJPiz2qfkZQGubVlrUWojAWF2Ps+LE6V/7mU9nYnylIherxtw4FeEP0x3DYd453o/qwon1qDWAkS34YDkg+eqFUuTkov6JHyWcne47CqB/HmI5luav6V0FzLkaDuhxlAnUh2cdEMPFWa3m5XKkU69Tbiuy22FELTExwSFpNzkndB+QHoEqfdh9W70mUS/B3cAJdv/L8YLHW/WB7bPaV0kx7sUsosBWYidEaW9MHNddS2YDFoxlqFMYzQ8qRmSWw21xszzw+0KDUe5AC5eo0vOjtIeZ/IPrz0f9oHZ0INQtoT8b9mDv4GrHnvPDkKsWz9YlUDeah5iMeVNjRf21mZL4/VfphklERJKw+8QT7eLc2RfBQHH4+LPRYMQp67W3B2zjxX1OWZJa5zIYXotU5TziLEb+zgypkzO372WJzzLXfT91i/4w3X4kcb7NHm8XWFQ1EW6+KMzXEIP4dwLIRAYvFk9KUn0+kXzw9CL7ZGj30hCgagIGm+W9002fq1q8jXSytZMd6i0fvJXKcSZIu9Mps4oXbO12a8=
      on:
        branch: master
    - provider: releases
      api_key:
        secure: ZgSKh4vMer7Wq1pKlf8CAtc0o0r3ztJtsQrHq5SRnnc8FQ+y92T05KBrExNz4DymSnI1PFrc0nqOKYZ3+VHzy/MUS/J0dyLklHUxxF0kKdpVfvYY7TxIzVrF9gXUnlSI1q5aov+MR8JGXmyvWNbNY8ihjUlc2Wl6/fGa1gHeeuoILc/YiOq4rlRe69x/aykt9O9wUnsIGrjCwujcwizlgBcG4BSf20zNGrBdFeU44yBhJUSdSPQ9F3the0r9J8LPkWJtMi7WKc1agHw8nZy1cfO1O1X1+s8/ScbldQVZKpnQra53Y5scqoosJw8gfOGuI/ifAtZhT0V0HWeobJFo0Lo4lcGaaJ1Hc508XbgNcCcchI9kCwVarnRAlqrfUj5Rj1AUKdcN97K2UFpdswZBvEjiMbtqRRrSdBwHuArhhQPZfqYnjVxPiPVBJ8WlsvnHbA+ePtj177bgcImteoJcjza02tR12ynN0lHs/U0RglUED04uPh5Q5nr9xNaeSzC4zOrjN3ui8R2e/6ACMROrs6V/LYPzdC22kbX/8NS+VBHgCFKtzTeCUGp9wFGN7rGWE52YoeBK+Y6qTtIHxnewbxz8sYpnMDw80xUPn2Kx2I5jfAEyWVx7NVi2Iiy08aV5e47JnGs6LQzfSh4BpEs7x8sGbXEFiShsgazQG0XmJxw=
      file:
      - after-effects
      - after-effects.asc
      skip_cleanup: true
      prerelease: true
      name: Relesae - ${TRAVIS_TAG}
      body: Please check the Changelogs at https://ae.prasadt.com/changelogs/.
      overwrite: true
      on:
        branch: master
        tags: true
matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_ENV="Pre-Release"
  - env: TEST_ENV="Cosmic-Docker"
notifications:
  email: false
  slack:
    rooms:
    - secure: i8WqqSQDZg3FbYwh0jpkw9ZEV4AqqAq9j1NzTZnD2YDm6P188eaaQ3nJaV67lavFSCkivg/Ar5hGNpQuojtdGAZ8wOEy+Wwk7iOkgItU6PucL8AmDNQ0LLTGXNbS87a36OSWfRvbzHvhIEPK9s6RNV2upNMglwNbco+BFDIG8Zng0gJS8n2UpGtq7RDUIfIQ1bYUNg5h+16fR/3tmDX0NAnevTu9J+mXRIZS/W8fGl4XPW6RpeNS3Lk/WqhmUHy1Wc7JXl9VU/ZoTmPAHWZxYnU9UNYExOY5ATVa5jEEtidUFMK+r4DPcVtG5RBpnZO8SiFRvaTuqRUX9CjJraZ/X3YedDOehre5R89g7lstJtlN5rUgiW0oIcuAxlaj0sNYVu8rDq/fYryR72sTlQAnO5CA3A4jjO1B5HOzVece4NoMJ1B/5GcYf1EJ3sSUyONClO/Mh/Ubsfg1d02fgDDSenm/zZJEB86kt3rkylg5V1eHK60+ycLhoTX+xIJKiUFHHRgMmgzKnHqyF+52z3bYRV1uVjhdi6q4I3H/cDx3fBts5eoQtjl+hDaArsaXlANz3oLd89g0sAqBrKgO++EcxgqeeWukSomgmJtPBivqnbg1RpAIK9zl9fjetD58FYL5i5gnYKpWTsICpZjgWqwqRmhnonkTdUbMnBsHol2HvQw=
    on_success: change
    on_failure: always
