sudo: false
language: bash
services:
- docker
before_install:
script:
- "./tests/test-shell-scripts"
matrix:
  fast_finish: true
notifications:
  slack:
    rooms:
      - secure: Pf9C4IsyUCmIv0jxcnAawLA1410vQ5oQWvBbA0g008omXBywD7VGnhCJbO24km5sVIAlZKFmUNYTdrRixveJB3bOZ1gAtePiFiASxZ4O+pT7rX/gcdTa9u3RcTftZXEk3CdZr3QTCCUzsklEkGckJg7AfKXV4utaYpt/c8RJf52PhjO5h062VxLB0D76+kilA9WoqDv9ko7M54ya9U+3EVv4hksmqSGhLNcIH/z7+8JsTUgYsX0RMtA94k/iNYLFeuC0guuy8sNmtrZ3zC1IH80RXNeI57DKRcOYDMPBDm+LI9W/3YwvSaICS792B3xtDfLpcsQ2cMebsziqKhFStbaJKnskdckMSq9TwlNLTG6Vi+zfxtQhVNPmNmd9oeQXtiqkcvX5M94tDm2R2Q2evWjkeqNbA3VGln/ExHrPUF2cI/NpJa5HLL3YTQdPZ8IftoWsnmdA4mfte3fcZ4bgOgp2Ayn1824WUx3tH20lW7LPDleiEW45W1oEe3Ka+jhwqchXreWlLfjGSeJ7drQC7g5S9o5Y7Sjv2aEojngk8/RIVjAxP3FAedGHX75FntQLD8sKRiXNZGkt4dWeYC3YRsocM9DmI3W7Bxw6eObKauKmVBn6C8sDZPRf8YjvC9tNpi84Q5m19a7xnKqm8ru/RKW9hjiiL/XhX/IjbCy5THo=
      - secure: x6Bs7lM7p8dZ35tUAkuLm0kTyp38kD6feKy6Ddyu/l0iTjawQb0jBmZDM+sHscTJvtchoz1PZcbcjMhhpHQ6jnN4uHG6m02pUEFLX8nrWGhxyrjnnY9YT2TIV2PERDgkgxk1+rQrJnvyEr8HYjafQM8GF2Vpl+8nKJVL/jz1wRlymqi0DkYgGMWmTzVWl7alh7GmErW9eNS1W3NBj+y2SBhhOUqqbg7Vrr2SA8cHDEJhDW1QCQI7LwDgnT48el6+C6xs7gRSVi0MUYGd6YJXZIrx5ayKZyLee1nlQryjXtAF59fhcwdQUqSeuskt9mJ6x9Ihdssl1JS/vA39X7t6WYNbQpW5YdLiizjhg9cfu7jToNCTRDYMTVTxmPm44XPuF+eSOrnumAZH+lvn/zOELHGzXfhHNRr+zAf8/VmnL5yhinbt/S8WGglvyDZOkoTXfL/aB1HWuDLc2tNfIZm8ZIYTbpB1vsWwTE8kxped42lQWKqCoMt4dBRnKCOYjIgiHr6LnKVeWDa2X4mnyib5+4fgI9cx44J2yC6kX9E+E/yfke0R0z68iDaaPxmRvs2MWGOwqEh6YgxkUMmt5fRkkTCYJig7kZNjR4zm03/VhIZ2HFZzLy+O+ziB60OjzAmP2CguYrB9NafQ0gjM3g/JEmYE/I2YmdCiz/j4C71FnWI=
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always
