# Install Config
version: 1
name: Polaris
author: Prasad T
# Configuraion
config:
    # Repository Flags
    add_repos:
        winehq: true
        docker: true
        mendeley: false
        googlecloud: true
        spotify: true
        vscode: true
        skype: true
        signal: false
        insync: true
        google: true
        kubernetes: false

    # Other Flags
    others:
        data_directory: data
        # Fetch Remote Data Files,
        # data_direcory must not be set to `data`, otherwise
        # local files will be overwriten.
        # false : Prefer local lists and ignore remote lists
        # true  : Prefer remote lists and ignore local lists
        prefer_local_flags: false
        purge_enabled: false
        keep_debs: true
        auto_yes: false
        # Simulate will never be overridden by remote config.
        # Hooks
        enable_pre: true
        enable_post: true
    # Packages to purge
    purge:
      - gnome-mines
      - gnome-sudoku
      - aisleriot
      - gnome-mahjongg
    # Install APT PAckages, Add PPAs & PIP
    install:
        # PPA List
        ppa:
          - ppa:dawidd0811/neofetch
          - ppa:yubico/stable
          - ppa:teejee2008/ppa
        # Python 2 Modules
        python2:
          - docker-compose
        # Python 3 Modules
        python3:
          - awscli
        # Debian packages:  .deb files
        # CSV format similar to lists
        debian_packages:
              - https://atom-installer.github.com/v1.23.2/atom-amd64.deb,Atom-Editor.deb
              - https://download.teamviewer.com/download/teamviewer_i386.deb,Teamviewer.deb
        # Whether to install Packages in list external
        apt_external: true
        apt_packages:
            # Admin related Stuff
            administration:
                - dconf-editor
                - htop
                - apt-xapian-index
                - gdebi
                - gparted
                - synaptic
                - bleachbit
                - nautilus-admin
            # Security Related Stuff
            security:
                - gufw
            # Productiviy & Office Tools & Writing Tools
            productivity:
                - empathy
                - evolution
                - polari
                - realmd
                - pandoc-data
                - pandoc
                - texstudio
                - texlive-fonts-extra
                - texlive-formats-extra
                - texlive-fonts-recommended
                - texlive-science
                - texlive-generic-extra
                - texlive-xetex
                - texlive-luatex
                - texlive-pstricks
                - texlive-science
                - texlive-extra-utils
                - texlive-lang-english
                - texlive-lang-other
                - texlive-font-utils
                - texlive-publishers
                - gummi
            # Multimedia Tools. Photo Editots Converting tools, plex etc.
            multimedia:
                - audacity
                - vlc
                - gimp
                - handbrake
                - handbrake-cli
                - rawtherapee
                - darktable
                - mpv
                - pavucontrol
                - cheese
            # Tools related to development.
            devtools:
                - curl
                - spyder
                - spyder3
                - git
                - shellcheck
                - ocl-icd-dev
                - opencl-headers
                - clinfo
                - vainfo
                - vdpauinfo
                - ocl-icd-libopencl1
                - ruby
                - ruby-dev
                - python-magic
                - putty
                - s3cmd
                - python3-pip
                - python-dateutil
                - python-pip-whl
                - python-pip
            # Everything Else
            # Which is conditional
            conditional_others:
                - mesa-opencl-icd
                - opencl-clhpp-headers
                - opencl-c-headers
                - arc-theme
                - icedtea-8-plugin
                - openjdk-8-jre
                - neofetch
                - gnome-online-miners
                - telepathy-accounts-signon
                - signon-ui-service
            # Packages supplied by external repositories & PPAs
            # Dont Mix packages provided by distribution and PPAs
            # Sometimes external repos and ppas fail, so better isolate it.
            external:
                - google-chrome-stable
                - spotify-client
                - code
                - timeshift
                - google-cloud-sdk
                - gcsfuse
                - docker-ce
        hooks:
            # Directory in which scripts are saved
            dir: "scripts"
            # Whether to use local Scripts. If Dir mentioned above
            # does not exists then the script will fail.
            # If false, the Dir is cleaned before downloading files.
            # Else only the scripts specified will be downloded.
            # If a file already exists, its overwrien.
            use_local: false
            # URL to retreive scripts from via curl or wget.
            baseurl:
            files:
                - scripts/test-pre.sh
                - scripts/test-pre-2.sh
                - scripts/test-post.sh
                - scripts/test-post-2.sh
